spring:
  application:
    name: java_proj1
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # flywaydb + validate
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    # open-in-view false
    open-in-view: true

  # flywaydb
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

logging:
  level:
    org.hibernate.SQL: debug
